$(document).ready( function() {
  console.log("main JS is linked");
  ///Start of Game Visuals
  $("#lane1").append('<img id=\"car1\" src="imgs/blueCar.png" />');
  $("#lane2").append('<img id=\"car2\" src="imgs/orangeCar.png" />');
  var car1 = document.getElementById('#car1');
  var car2 = document.getElementById('#car2');
  // var initialState = $('#document').clone(true);
  $("#msgDisplay").append("Imagine a really cool countdown");
  //   if ($(this).css("padding-left") = "1700px"){
  //     console.log($(this) + " is the winner!");
  //   };
  // $.when($('#car1' || '#car2').css("padding-left") = "1700px").then(declareWinner());
  // var car1.val() = 97;
  // var car2 = document.getElementById('#car2');
  // function resetGame () {
  //   $('#document').replaceWith(initialState.clone(true));
  // }

  $(document).on("keypress", function(event) {
    // console.log(event);
    $('#msgDisplay').empty();
    if(event.originalEvent.charCode == 97) {
      // console.log("you pressed A");
      carMover1();
    } else if (event.originalEvent.charCode == 108) {
      // console.log("you pressed L")
      carMover2();
    } else if (event.originalEvent.charCode == 48) {
      console.log("you pressed 0");
      resetGame();
      // countdownV1();
    } else {
      console.log("you didnt press A, L, or 0")
      /* use .one & append method to notify people once they cant use keys besides A, L, 0*/
    }
  });
});


///keypress script
// $(document).on("keypress", function(event) {
//   // console.log(event);
//   $('#msgDisplay').empty();
//   if(event.originalEvent.charCode == 97) {
//     // console.log("you pressed A");
//     carMover1();
//   } else if (event.originalEvent.charCode == 108) {
//     // console.log("you pressed L")
//     carMover2();
//   } else if (event.originalEvent.charCode == 48) {
//     console.log("you pressed 0");
//     resetGame();
//     // countdownV1();
//   } else {
//     console.log("you didnt press A, L, or 0")
//     /* use .one & append method to notify people once they cant use keys besides A, L, 0*/
//   }
// });

///car movement script
// document.getElementById("car1").on("event" <-- used to precede carmover function

// Car mover v.1 function carMover1() {
//   console.log("carMover triggered");
//   var currentPadding = $('#car1').css('padding-left'); // replace #car1 w/ this ultimately
//   $('#car1').css('padding-left', currentPadding + 10);
// }

/// Maybe do Object Oriented / car constructor? Would allow me to set an interal value
// to the same as my charCode which might associate the two together. Or maybe attaching
// the carMover function to a prototype?

function carMover1() {
    // console.log("carMover triggered");
    $('#car1').css("padding-left", "+=20");
    // console.log($('#car1').css("padding-left"));
    declareWinner();
}

function carMover2() {
    // console.log("carMover triggered");
    $('#car2').css("padding-left", "+=20");
    declareWinner();
}

function declareWinner () {
  if ($('#car1').css("padding-left") === "1700px") {
    // $('#msgDisplay').append($(this) + "has won the race!");
    $('#msgDisplay').append("Car 1 has won the race!");
  } else if ($('#car2').css("padding-left") === "1700px"){
    // $('#msgDisplay').append($(this) + "has won the race!");
    $('#msgDisplay').append("Car 2 has won the race!");
  }
}


///countdown script
// window.setTimeout(countdownV2(), 1000)
// function countdownV2() {
//   $('#msgDisplay').append("3");
//   $('#msgDisplay').append("2");
//   $('#msgDisplay').append("1");
//   $('#msgDisplay').append("GO!");
// }



// function countdownV1() {
//   var counter = 3;
//   while (counter > 0) {
//     $('#msgDisplay').append([counter]);
//     counter = counter - 1;
//     window.setTimeout(1000);
//   }
// }


/* why was event.originalEvent.charCode used:
the keycodes I looked up online did not correctly correspond to the keys
I wanted to use so w/ Matt's help, I was able to find the correct keycodes
by moving through the object that was generated by console.log(event).
After changing the codes to the ones found in the object, my intended keys and
their keycodes were now working as intended
*/


/*How to limit the keypress to one trigger? using .one only allows 1 key to be pressed
total whereas I need to prevent holding the key from triggering a continous firing of
my event */
/* ^^^^ If I cant figure this out, rename game to dragrace and make it about reaction time*/
