var car1;
var car2;


// $(document).ready( function() {
//   console.log("main JS is linked");
//   ///Start of Game Visuals
//   $("#lane1").append('<img class=\"car1\" src="imgs/blueCar.png" />');
//   $("#lane2").append('<img class=\"car2\" src="imgs/orangeCar.png" />');
//   $("#startMsg").append("To begin, press enter");
// })


///car movement script
// function carMover(){
//
// }

///keypress script
$(document).on("keypress", function(event) {
  // console.log(event);
  if(event.originalEvent.charCode == 97) {
    console.log("you pressed A")
  } else if (event.originalEvent.charCode == 108) {
    console.log("you pressed L")
  } else if (event.originalEvent.charCode == 48) {
    console.log("you pressed 0")
  } else {
    console.log("you didnt press A, L, or 0")
  }
});

/* why was event.originalEvent.charCode used:
the keycodes I looked up online did not correctly correspond to the keys
I wanted to use so w/ Matt's help, I was able to find the correct keycodes
by moving through the object that was generated by console.log(event).
After changing the codes to the ones found in the object, my intended keys and
their keycodes were now working as intended
*/






//animation effect
