var car1;
var car2;


$(document).ready( function() {
  console.log("main JS is linked");
  ///Start of Game Visuals
  $("#lane1").append('<img id=\"car1\" style="padding-left: 0;" src="imgs/blueCar.png" />');
  $("#lane2").append('<img id=\"car2\" src="imgs/orangeCar.png" />');
  $("#startMsg").append("To begin, press enter");
});


///keypress script
$(document).on("keypress", function(event) {
  // console.log(event);
  if(event.originalEvent.charCode == 97) {
    console.log("you pressed A");
    carMover();
  } else if (event.originalEvent.charCode == 108) {
    console.log("you pressed L")
  } else if (event.originalEvent.charCode == 48) {
    console.log("you pressed 0")
  } else {
    console.log("you didnt press A, L, or 0")
    /* use .one & append method to notify people once they cant use keys besides A, L, 0*/
  }
});

///car movement script
// document.getElementById("car1").on("event" <-- used to precede carmover function

// Car mover v.1 function carMover1() {
//   console.log("carMover triggered");
//   var currentPadding = $('#car1').css('padding-left'); // replace #car1 w/ this ultimately
//   $('#car1').css('padding-left', currentPadding + 10);
// }

function carMover() {
    console.log("carMover triggered");
    $('#car1').css("padding-left", "+=10");
}

/* why was event.originalEvent.charCode used:
the keycodes I looked up online did not correctly correspond to the keys
I wanted to use so w/ Matt's help, I was able to find the correct keycodes
by moving through the object that was generated by console.log(event).
After changing the codes to the ones found in the object, my intended keys and
their keycodes were now working as intended
*/


/*How to limit the keypress to one trigger? using .one only allows 1 key to be pressed
total whereas I need to prevent holding the key from triggering a continous firing of
my event */
/* ^^^^ If I cant figure this out, rename game to dragrace and make it about reaction time*/






//animation effect
